<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Booked.Identity.Application\Booked.Identity.Application.csproj" />
    <ProjectReference Include="..\Booked.Identity.Domain\Booked.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\shared\Booked.Shared.BuildingBlocks\Booked.Shared.BuildingBlocks.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
  </ItemGroup>

</Project>
